version: '3.9'

services:

  database:
    profiles: [ "all" ]
    stdin_open: true  # -i
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-mongo
      network: host
      args:
        - TZ=$TZ
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./mdbdata:/data/db
      - ./dump:/dump
      - ./scripts/init_db.js:/docker-entrypoint-initdb.d/init_db.js:ro
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 3

  redis_app:
    profiles: [ "core", "all" ]
    image: redis:latest
    command: redis-server  --appendonly yes
    volumes:
      - ./redis-vol:/data

  backend:
    profiles: [ "backend","core-only", "all" ]
    stdin_open: true  # -i
    tty: true         # -t
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - TZ=$TZ
    image: python.$STACK
    privileged: true
    volumes:
      - ./backend:/app
      - .env:/app/.env
      - ./sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEB_CONCURRENCY=$WEB_CONCURRENCY
      - PORT=8225
    links:
      - database
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3

  client:
    profiles: [ "core-only", "all" ]
    stdin_open: true  # -i
    tty: true         # -t
    build:
      context: .
      dockerfile: Dockerfile-webclient
      network: host
      args:
        - TZ=$TZ
    image: python.admin-$STACK
    volumes:
      - ./web-client:/app
      - ./uploads:/uploads
      - .env-client:/app/.env
    environment:
      - WEB_CONCURRENCY=$WEB_CONCURRENCY
      - PORT=8526
    links:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3

  automation:
    profiles: [ "all" ]
    stdin_open: true  # -i
    tty: true
    build:
      context: automations
      dockerfile: Dockerfile
      network: host
      args:
        - TZ=$TZ
    image: automations.$STACK
    volumes:
      - ./automations:/automations
    privileged: true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  nginx:
    profiles: [ "core-only", "all" ]
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - database
      - backend
      - client
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${CLIENT_PORT}:${CLIENT_PORT}