FROM python:3.11.2-bullseye


LABEL maintainer="Alessio Gerace <a.gerace@inrim.it>"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND noninteractive
ARG TZ
ARG REQUIREMENTS
ENV REQUIREMENTS_SCRIPT=${REQUIREMENTS}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get -y dist-upgrade
RUN apt-get install -y build-essential python3-dev  git wget curl
RUN apt-get install -y ldap-utils libldap-dev libsasl2-dev python3-dev python3-pip python3-wheel
RUN apt-get install -y xfonts-75dpi libxrender1 fontconfig xfonts-base
RUN apt-get install -y gcc g++ locales locales-all
RUN apt-get clean

RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb
RUN dpkg -i wkhtmltox_0.12.6.1-2.bullseye_amd64.deb
RUN rm ./wkhtmltox_0.12.6.1-2.bullseye_amd64.deb

RUN wkhtmltopdf --version


ENV LC_ALL it_IT.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8


COPY ./start.sh /start.sh
COPY ./gunicorn_conf.py /gunicorn_conf.py
COPY . /apps

RUN chmod +x /$REQUIREMENTS_SCRIPT
RUN /apps/$REQUIREMENTS_SCRIPT 'web-client'


ENV PYTHONPATH=/app

ENTRYPOINT ["/start.sh"]


