FROM python:3.11.0-bullseye

LABEL maintainer="Alessio Gerace <a.gerace@inrim.it>"
ARG APP_GROUP
ARG APP_NAME
ARG TZ
ARG REQUIREMENTS
ENV REQUIREMENTS_SCRIPT=${REQUIREMENTS}


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND noninteractive


RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update;  \
    apt-get upgrade;  \
    apt-get install -y \
            build-essential python3-dev git \
            ldap-utils libldap-dev libsasl2-dev python3-dev \
            gcc g++ locales locales-all; \
    apt-get clean

ENV LC_ALL it_IT.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

COPY ./$REQUIREMENTS_SCRIPT /$REQUIREMENTS_SCRIPT
RUN $REQUIREMENTS_SCRIPT

COPY ./start.sh /start.sh
RUN chmod +x /start.sh

COPY ./gunicorn_conf.py /gunicorn_conf.py

WORKDIR /app
ENV PYTHONPATH=/app
EXPOSE 80

COPY ./web-client /app
COPY ./web-client/${APP_GROUP}/${APP_NAME}/docker/config.json /app/config.json

#RUN curl -k -O -L https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb && \
#    apt-get install -y --no-install-recommends ./wkhtmltox_0.12.6-1.buster_amd64.deb && \
#    rm ./wkhtmltox_0.12.6-1.buster_amd64.deb

RUN wkhtmltopdf --version

CMD ["/start.sh"]


