version: '3.9'

services:

  {{module_name}}:
      stdin_open: true  # -i
      tty: true         # -t
      build:
        context: /apps/.
        dockerfile: Dockerfile-app
        network: host
        args:
          - TZ={{ tz }}
          - APP_GROUP={{module_group}}
          - APP_NAME={{module_name}}
      image: python.{{module_group}}-{{module_name}}
      environment:
        - WEB_CONCURRENCY=$WEB_CONCURRENCY
        - PORT={{ internal_port }}
      links:
        - backend
      restart: always
      deploy:
        restart_policy:
          condition: on-failure
          max_attempts: 3

    nginx-{{module_name}}:
        build:
          context: /apps/.
          dockerfile: Dockerfile-nginx
          network: host
          args:
            - APP_GROUP={{module_group}}
            - APP_NAME={{module_name}}
        image: nginx.{{module_group}}-{{module_name}}
        depends_on:
          - {{module_name}}
        ports:
          - "{{ port }}:{{ port }}"

