# generated by datamodel-codegen:
#   filename:  global_params.json
#   timestamp: 2026-08-19T07:46:14+00:00

from __future__ import annotations

import datetime
import zoneinfo
from typing import Optional

from ozonenv.core.BaseModels import BasicModel, CoreNestedModel
from pydantic import Field


class GlobalParams(BasicModel):

    rec_name: Optional[str] = Field('', title='Rec Name')
    value: Optional[str] = Field('', title='Value')

    
    @classmethod
    def get_version(cls):
        return '2026-08-19T07:46:14.046725+00:00'
        
    @classmethod
    def schema(cls) -> dict:
        return {'id': '6a855f466fe6f6d549b4b7fe', 'data_model': '', 'rec_name': 'global_params', 'app_code': '', 'parent': '', 'process_id': '', 'process_task_id': '', 'data_value': {'deleted': '0.00'}, 'owner_name': '', 'deleted': 0.0, 'list_order': 13, 'owner_uid': '', 'owner_mail': '', 'owner_function': '', 'owner_function_type': '', 'owner_sector': '', 'owner_sector_id': 0, 'owner_personal_type': '', 'owner_job_title': '', 'update_uid': '', 'sys': True, 'default': False, 'active': True, 'demo': False, 'childs': [], 'create_datetime': datetime.datetime(2026, 8, 19, 7, 46, 2, 655269, tzinfo=zoneinfo.ZoneInfo(key='UTC')), 'update_datetime': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), 'title': 'Parametri Globali', 'path': '', 'parent_name': '', 'components': [{'label': 'Name', 'tableView': True, 'key': 'rec_name', 'type': 'textfield', 'input': True}, {'label': 'Value', 'autoExpand': False, 'tableView': True, 'key': 'value', 'type': 'textarea', 'input': True}, {'type': 'button', 'label': 'Submit', 'key': 'submit', 'disableOnInvalid': True, 'input': True, 'tableView': False}], 'links': {}, 'type': 'resource', 'no_cancel': 0, 'display': 'form', 'action': '', 'tags': [], 'settings': {}, 'properties': {'rheader': '1', 'rfooter': '1', 'sort': 'rec_name:asc', 'send_mail_create': '0', 'send_mail_update': '0', 'models_groups': {'rules': [{'groups': ['admin'], 'actions': {'read': True, 'create': True, 'update': True, 'delete': True, 'export': True}}, {'groups': ['technical_operator'], 'actions': {'read': True, 'create': True, 'update': True, 'delete': False, 'export': True}}]}, 'models_restricted_fields': {'record_rulse': [{'filters': {'owner_uid': {'$eq': {'var': 'user.uid'}}}, 'actions': {'read': True, 'create': True, 'update': True, 'delete': True}}]}}, 'handle_global_change': 1, 'process_tenant': '', 'make_virtual_model': False, 'authenticate': True, 'projectId': 'core'}      
          
    @classmethod
    def json_schema(cls) -> dict[str, Any]:
        return {'properties': {'rec_name': {'default': '', 'title': 'Rec Name', 'type': 'string'}, 'value': {'default': '', 'title': 'Value', 'type': 'string'}}, 'title': 'global_params', 'type': 'object'}
                
    @classmethod
    def all_fields(cls) -> list:
        return {'rec_name': {'label': 'Name', 'tableView': True, 'key': 'rec_name', 'type': 'textfield', 'input': True, 'properties': {}, 'validate': {}}, 'value': {'label': 'Value', 'autoExpand': False, 'tableView': True, 'key': 'value', 'type': 'textarea', 'input': True, 'properties': {}, 'validate': {}}} 
        
    @classmethod
    def secret_fields(cls) -> list:
        return []
        
    @classmethod
    def select_fields(cls):
        return {}

    @classmethod
    def select_options(cls, key: str = None, update_options: dict = None):
        options = {}
        if key and update_options and key in options:
            options[key] = update_options.copy()
        return options.copy()
        
    @classmethod
    def datetime_fields(cls):
        return {'update_datetime': {'transform': {'type': 'datetime'}}, 'create_datetime': {'transform': {'type': 'datetime'}}}
        
    @classmethod
    def get_unique_fields(cls) -> list:
        return ['rec_name']
        
    @classmethod
    def computed_fields(cls):
        return {}
    
    @classmethod
    def no_clone_field_keys(cls):
        return ['rec_name']
    
    @classmethod
    def tranform_data_value(cls):
        return {}    
    
    @classmethod
    def fields_limit_value(cls):
        return {}     
    
    @classmethod
    def create_task_action(cls):
        return []
    
    @classmethod
    def fields_properties(cls):
        return {}

    @classmethod
    def get_restricted_fields(cls) -> list:
        return []

    @classmethod
    def get_field_rules(cls) -> dict:
        return {}

    @classmethod
    def get_field_rules_conditions(cls) -> dict:
        return {}

    @classmethod
    def default_hidden_fields(cls):
        return []

    @classmethod
    def default_readonly_fields(cls):
        return []
    
    @classmethod
    def default_required_fields(cls):
        return []   
         
    @classmethod
    def filter_keys(cls):
        return ['rec_name', 'value']  

    @classmethod
    def table_columns(cls) -> dict:
        return {'rec_name': 'Name', 'value': 'Value'}
        
    @classmethod
    def get_data_model(cls):
        return ""
    
    @classmethod
    def conditional(cls) -> dict(str, dict):
        return {}

    @classmethod
    def logic(cls) -> dict(str, dict):
        return {}
    
    @classmethod
    def conditional(cls) -> dict(str, dict):
        return {}
        
    @classmethod
    def model_depends(cls):
        return []
        
    @classmethod
    def nested_datetime_fields(cls):
        return {}
        
    @classmethod
    def nested_transform_data_value(cls):
        return {}
    
    @classmethod
    def file_fields(cls) -> dict:
        return {}

